import type { Metadata } from "next";
import "@/styles/globals.scss";
import { AuthProvider } from "../context/AuthContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { roboto, firaSans } from "@/app/fonts/_fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${roboto.variable} ${firaSans.variable}`}
			suppressHydrationWarning
		>
			<head>
				<script src="/scripts/set-theme.js" />
			</head>
			<body className="">
				<AuthProvider>
					<ThemeProvider>{children}</ThemeProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
